"""Update product tonkho to be nullable with default

Revision ID: bfceda8b378f
Revises: 
Create Date: 2025-07-29 10:39:12.117954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bfceda8b378f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_productpricehistory_product_masp'), table_name='productpricehistory')
    op.drop_table('productpricehistory')
    op.drop_index(op.f('ix_invoice_mahd'), table_name='invoice')
    op.drop_index(op.f('ix_invoice_makh'), table_name='invoice')
    op.drop_table('invoice')
    op.drop_index(op.f('ix_product_tensp_khongdau'), table_name='product')
    op.drop_table('product')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_customer_tenkh'), table_name='customer')
    op.drop_index(op.f('ix_customer_tenkh_khongdau'), table_name='customer')
    op.drop_table('customer')
    op.drop_index(op.f('ix_invoicedetail_mahd'), table_name='invoicedetail')
    op.drop_index(op.f('ix_invoicedetail_masp'), table_name='invoicedetail')
    op.drop_table('invoicedetail')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoicedetail',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('mahd', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('masp', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('donvi', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sl', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('dongia', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('ck', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('thanhtien', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['mahd'], ['invoice.mahd'], name=op.f('invoicedetail_mahd_fkey')),
    sa.ForeignKeyConstraint(['masp'], ['product.masp'], name=op.f('invoicedetail_masp_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('invoicedetail_pkey'))
    )
    op.create_index(op.f('ix_invoicedetail_masp'), 'invoicedetail', ['masp'], unique=False)
    op.create_index(op.f('ix_invoicedetail_mahd'), 'invoicedetail', ['mahd'], unique=False)
    op.create_table('customer',
    sa.Column('makh', sa.INTEGER(), server_default=sa.text("nextval('customer_makh_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('tenkh', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('diachi_sdt', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ghichu', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tongtienhang', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('tongchietkhau', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('tongthanhtoan', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('khhdathanhtoan', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('conno', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('tenkh_khongdau', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('makh', name='customer_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_customer_tenkh_khongdau'), 'customer', ['tenkh_khongdau'], unique=False)
    op.create_index(op.f('ix_customer_tenkh'), 'customer', ['tenkh'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('user_pkey'))
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('product',
    sa.Column('masp', sa.INTEGER(), server_default=sa.text("nextval('product_masp_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('tensp', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tensp_khongdau', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('donvi', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('dongia', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('tonkho', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('ghichu', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('masp', name='product_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_product_tensp_khongdau'), 'product', ['tensp_khongdau'], unique=False)
    op.create_table('invoice',
    sa.Column('mahd', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('makh', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ngaylap', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('khhdathanhtoan', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('nguoilap', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ghichu', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('congtienhang', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('congchietkhau', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('conno', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('trangthai', postgresql.ENUM('PAID', 'UNPAID', 'CANCELLED', name='invoicestatus'), autoincrement=False, nullable=False),
    sa.Column('ngay_huy', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('nguoi_huy', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['makh'], ['customer.makh'], name=op.f('invoice_makh_fkey')),
    sa.PrimaryKeyConstraint('mahd', name=op.f('invoice_pkey'))
    )
    op.create_index(op.f('ix_invoice_makh'), 'invoice', ['makh'], unique=False)
    op.create_index(op.f('ix_invoice_mahd'), 'invoice', ['mahd'], unique=False)
    op.create_table('productpricehistory',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_masp', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('effective_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('recorded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_masp'], ['product.masp'], name=op.f('productpricehistory_product_masp_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('productpricehistory_pkey'))
    )
    op.create_index(op.f('ix_productpricehistory_product_masp'), 'productpricehistory', ['product_masp'], unique=False)
    # ### end Alembic commands ###
